# Generated by Django 5.0.6 on 2024-06-20 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_adltest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adltest',
            name='valor1',
            field=models.IntegerField(default=False),
        ),
    ]
